### ISSUE TITLE
Having some trouble with the function to detect collision with itself.

### ISSUE THREAD

**Issue by eggdev** [beggers23/SnakeGame#2]
So my game-state is 600 x 600.. when the snake head is at 510px left, and the snakes body is at 510px top, it registers as a loss because I figured it the snakeHead Top and Left are equal to body[i].top and left, it should call the game...

Not sure if these words make sense

**Comment by gittheking** [comment]
Collision was solved before i was able to consult, so we went over some strategy for fading the snake's color as it increases
